name: guake
version: 3.6.3
summary: Top-down terminal for Gnome, inspired by the terminal used in Quake
description: |
  Guake is a dropdown terminal made for the GNOME desktop environment.
  Guake's style of window is based on an FPS game,
  and one of its goals is to be easy to reach.
icon: guake.png

grade: devel
confinement: devmode
base: core18

layout:
  /usr/local/share:
    bind: $SNAP/usr/local/share

slots:
  dbus-guake:
    interface: dbus
    bus   : session
    name: org.guake3.RemoteControl

environment:
  PYTHONPATH: $PYTHONPATH:$SNAP/usr/local/lib/python3.6/dist-packages

apps:
  guake:
    command:  usr/local/bin/guake
    desktop: usr/local/share/applications/guake.desktop
    extensions: [gnome-3-28]
    slots:
     - dbus-guake
    plugs:
     - gsettings  
     - home

parts:
  guake:
    source-type: git
    source: https://github.com/Guake/guake/
    source-tag: 3.6.3
    plugin: make
    make-install-var: PREFIX
    make-parameters:
      - DESTDIR=$SNAPCRAFT_PART_INSTALL
    build-packages:
      - gettext
      - libglib2.0-dev
      - gsettings-desktop-schemas
    stage-packages:
      - gir1.2-keybinder-3.0
      - gir1.2-notify-0.7
      - gir1.2-vte-2.91
      - gir1.2-wnck-3.0
      - gir1.2-gtk-3.0
      - libkeybinder-3.0-0
      - libutempter0
      - python3-distutils
      - python3-pip
      - python3-setuptools
      - python3-gi-cairo
      - python3-cairo
      - python3-dbus
      - python3-gi
      - python-gobject-2
    override-build: |
      snapcraftctl build
      sed -i 's|#!/root/parts/guake/install/usr/bin/python3|#!/usr/bin/env python3|' $SNAPCRAFT_PART_INSTALL/usr/local/bin/guake




